const { Router } = require('express');
const { query, pool } = require('./db');
const router = Router();
let realtime = () => {};
router.setRealtime = fn => { realtime = fn; return router; };
router.get('/snapshot', async (req,res,next)=>{try{const [p,t,c]=await Promise.all([query('SELECT id,name,sku,category,purchase_price AS "purchasePrice",sale_price AS "salePrice",quantity,min_stock AS "minStock",unit,created_at AS "createdAt",updated_at AS "updatedAt" FROM products ORDER BY created_at DESC'),query('SELECT id,type,product_id AS "productId",product_name AS "productName",quantity,note,date FROM transactions ORDER BY date DESC'),query('SELECT id,name,kind,phone,email,note,created_at AS "createdAt" FROM contacts ORDER BY created_at DESC')]);res.json({products:p.rows,transactions:t.rows,contacts:c.rows})}catch(e){next(e)}});
router.put('/snapshot', async (req,res,next)=>{const s=req.body||{}, c=await pool.connect();try{await c.query('BEGIN');for(const p of s.products||[])await c.query('INSERT INTO products(id,name,sku,category,purchase_price,sale_price,quantity,min_stock,unit,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,sku=EXCLUDED.sku,category=EXCLUDED.category,purchase_price=EXCLUDED.purchase_price,sale_price=EXCLUDED.sale_price,quantity=EXCLUDED.quantity,min_stock=EXCLUDED.min_stock,unit=EXCLUDED.unit,updated_at=EXCLUDED.updated_at',[p.id,p.name,p.sku,p.category,p.purchasePrice||0,p.salePrice||0,p.quantity||0,p.minStock||0,p.unit||null,p.createdAt||new Date().toISOString(),p.updatedAt||new Date().toISOString()]);for(const t of s.transactions||[])await c.query('INSERT INTO transactions(id,type,product_id,product_name,quantity,note,date) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO NOTHING',[t.id,t.type,t.productId,t.productName,t.quantity,t.note||'',t.date||new Date().toISOString()]);for(const x of s.contacts||[])await c.query('INSERT INTO contacts(id,name,kind,phone,email,note,created_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,kind=EXCLUDED.kind,phone=EXCLUDED.phone,email=EXCLUDED.email,note=EXCLUDED.note',[x.id,x.name,x.kind,x.phone||'',x.email||'',x.note||'',x.createdAt||new Date().toISOString()]);await c.query('COMMIT');realtime({type:'snapshot.changed'});res.json({ok:true})}catch(e){await c.query('ROLLBACK');next(e)}finally{c.release()}});

router.get('/products', async (req,res,next)=>{try{const r=await query('SELECT id,name,sku,category,purchase_price AS "purchasePrice",sale_price AS "salePrice",quantity,min_stock AS "minStock",unit,created_at AS "createdAt",updated_at AS "updatedAt" FROM products ORDER BY created_at DESC');res.json(r.rows)}catch(e){next(e)}});
router.post('/products', async (req,res,next)=>{const p=req.body;const client=await pool.connect();try{await client.query('BEGIN');const now=new Date().toISOString();await client.query('INSERT INTO products(id,name,sku,category,purchase_price,sale_price,quantity,min_stock,unit,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10)',[p.id,p.name,p.sku,p.category,p.purchasePrice||0,p.salePrice||0,p.quantity||0,p.minStock||0,p.unit||null,now]);if(Number(p.quantity)>0)await client.query('INSERT INTO transactions(id,type,product_id,product_name,quantity,note,date) VALUES($1,$2,$3,$4,$5,$6,$7)',[p.txId||`${p.id}-opening`,'IN',p.id,p.name,p.quantity,'رصيد افتتاحي',now]);await client.query('COMMIT');const out={...p,createdAt:now,updatedAt:now};realtime({type:'product.created',data:out});res.status(201).json(out)}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
router.get('/transactions', async (req,res,next)=>{try{const r=await query('SELECT id,type,product_id AS "productId",product_name AS "productName",quantity,note,date FROM transactions ORDER BY date DESC');res.json(r.rows)}catch(e){next(e)}});
router.post('/transactions', async (req,res,next)=>{const t=req.body;const client=await pool.connect();try{await client.query('BEGIN');const p=(await client.query('SELECT * FROM products WHERE id=$1 FOR UPDATE',[t.productId])).rows[0];if(!p){await client.query('ROLLBACK');return res.status(404).json({error:'PRODUCT_NOT_FOUND'});}const q=Number(t.quantity);if(!Number.isFinite(q)||q<=0||(t.type==='OUT'&&Number(p.quantity)<q)){await client.query('ROLLBACK');return res.status(400).json({error:'INVALID_QUANTITY'});}const nextQty=t.type==='IN'?Number(p.quantity)+q:Number(p.quantity)-q;const date=t.date||new Date().toISOString();await client.query('UPDATE products SET quantity=$1,updated_at=$2 WHERE id=$3',[nextQty,date,p.id]);await client.query('INSERT INTO transactions(id,type,product_id,product_name,quantity,note,date) VALUES($1,$2,$3,$4,$5,$6,$7)',[t.id,t.type,p.id,p.name,q,t.note||'',date]);await client.query('COMMIT');const out={...t,productName:p.name,quantity:q,date};realtime({type:'inventory.changed',data:out});res.status(201).json(out)}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
router.get('/contacts', async (req,res,next)=>{try{const r=await query('SELECT id,name,kind,phone,email,note,created_at AS "createdAt" FROM contacts ORDER BY created_at DESC');res.json(r.rows)}catch(e){next(e)}});
router.post('/contacts', async (req,res,next)=>{try{const c=req.body, now=new Date().toISOString();await query('INSERT INTO contacts(id,name,kind,phone,email,note,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[c.id,c.name,c.kind,c.phone||'',c.email||'',c.note||'',now]);realtime({type:'contact.created',data:{...c,createdAt:now}});res.status(201).json({...c,createdAt:now})}catch(e){next(e)}});
module.exports=router;
